In [2]:
import numpy as np

In [3]:
np.array([1,2,3,])

array([1, 2, 3])

In [4]:
np.array([1,2,3,], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [6]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [47]:
matrix= [[0,2,3],[2,0,4],[3,4,5]]

In [48]:
np.array(matrix)

array([[0, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])

In [49]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
np_matrix = np.array(matrix)

In [51]:
np_matrix.all()

False

In [52]:
np_matrix

array([[0, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])

In [53]:
np_matrix.any()

True

In [54]:
np_matrix[::-1]

array([[3, 4, 5],
       [2, 0, 4],
       [0, 2, 3]])

# 1.2 NumPy Standard Data Types

In [68]:
np_array = np.array(matrix, dtype='float64')
np_array.dtype

dtype('float64')

In [73]:
np_array = np_array.astype(np.float32)
print(f"Type after moving to float32 {np_array.dtype}")
print('Now as np.bool_')
print(np_array.astype(np.bool_))
print('Now as string_')
print(np_array.astype(np.str_))

Type after moving to float32 float32
Now as np.bool_
[[False  True  True]
 [ True False  True]
 [ True  True  True]]
Now as string_
[['0.0' '2.0' '3.0']
 ['2.0' '0.0' '4.0']
 ['3.0' '4.0' '5.0']]


## 1.3 Numpy Dimension

In [80]:
np_array.ndim

2

In [76]:
scalar = np.array(12)
scalar.ndim

0

In [78]:
vector = np.array([1,2,3])
vector.ndim

1

In [82]:
tensor = np.array([[1,2,3],[4,5,6]])
tensor.ndim

2

## 1.3.1 Add and delete dimensions

In [102]:
vector = np.array([1,2,3],ndmin=3)
vector

array([[[1, 2, 3]]])

In [104]:
# Adding dimensions
vector = np.expand_dims(vector, axis=0)
vector

array([[[[[1, 2, 3]]]]])

In [105]:
# Removing dimensions
expanded_vector = np.squeeze(vector, axis=0)
expanded_vector = np.squeeze(expanded_vector, axis=0)
expanded_vector

array([[[1, 2, 3]]])